# Generated by Django 2.2.1 on 2019-05-15 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clsname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Cno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Cname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Tno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Tname', models.CharField(max_length=20)),
                ('Tsex', models.BooleanField()),
                ('Tbirthday', models.DateTimeField(null=True)),
                ('Prof', models.CharField(max_length=20, null=True)),
                ('Dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='app01.Depart')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Sno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Sname', models.CharField(default=None, max_length=20)),
                ('Ssex', models.BooleanField(default=None)),
                ('Sbirthday', models.DateTimeField(default=None, null=True)),
                ('Cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app01.Classes')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.DecimalField(decimal_places=1, max_digits=4)),
                ('Cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='app01.Course')),
                ('Stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='app01.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Tea',
            field=models.ManyToManyField(related_name='courses', to='app01.Teacher'),
        ),
        migrations.AddField(
            model_name='classes',
            name='Dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='app01.Depart'),
        ),
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together={('Clsname', 'Dep')},
        ),
    ]
